#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : opa-fm
Version  : 10.10.0.0.444
Release  : 2
URL      : https://github.com/intel/opa-fm/archive/v10.10.0.0.444.tar.gz
Source0  : https://github.com/intel/opa-fm/archive/v10.10.0.0.444.tar.gz
Summary  : OPA Fabric Manager
Group    : Development/Tools
License  : BSD-3-Clause
Requires: opa-fm-bin = %{version}-%{release}
Requires: opa-fm-data = %{version}-%{release}
Requires: opa-fm-license = %{version}-%{release}
Requires: opa-fm-man = %{version}-%{release}
Requires: opa-fm-services = %{version}-%{release}
BuildRequires : expat-dev
BuildRequires : openssl-dev
BuildRequires : pkgconfig(json-c)
BuildRequires : pkgconfig(zlib)
BuildRequires : rdma-core-dev
BuildRequires : util-linux
BuildRequires : zlib-dev
Patch1: build_version.patch

%description
OPA Fabric Manager
-------------------
* To build the RPM and SRPM:
1. mkdir -p $HOME/rpmbuild/{SOURCES,RPMS,SRPMS}
2. ./Esm/update_opa-fm_spec.sh opa-fm.spec.in opa-fm.spec
3. tar czf $HOME/rpmbuild/SOURCES/opa-fm.tar.gz --exclude-vcs .
4. rpmbuild -ba ./opa-fm.spec

%package bin
Summary: bin components for the opa-fm package.
Group: Binaries
Requires: opa-fm-data = %{version}-%{release}
Requires: opa-fm-license = %{version}-%{release}
Requires: opa-fm-services = %{version}-%{release}

%description bin
bin components for the opa-fm package.


%package data
Summary: data components for the opa-fm package.
Group: Data

%description data
data components for the opa-fm package.


%package license
Summary: license components for the opa-fm package.
Group: Default

%description license
license components for the opa-fm package.


%package man
Summary: man components for the opa-fm package.
Group: Default

%description man
man components for the opa-fm package.


%package services
Summary: services components for the opa-fm package.
Group: Systemd services

%description services
services components for the opa-fm package.


%prep
%setup -q -n opa-fm-10.10.0.0.444
cd %{_builddir}/opa-fm-10.10.0.0.444
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1585257976
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}  || cd Esm && ./fmbuild


%install
export SOURCE_DATE_EPOCH=1585257976
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/opa-fm
cp %{_builddir}/opa-fm-10.10.0.0.444/Esm/debian/copyright %{buildroot}/usr/share/package-licenses/opa-fm/31b5b4b9993aab20f8d12d5a46d638e962b77f9c
cp %{_builddir}/opa-fm-10.10.0.0.444/Esm/ib/doc/cs/COPYING %{buildroot}/usr/share/package-licenses/opa-fm/5868056e5347f049ca07096a4a426c0e4a71a474
cp %{_builddir}/opa-fm-10.10.0.0.444/Esm/ib/test/cs/COPYING %{buildroot}/usr/share/package-licenses/opa-fm/492fce15e8c89e8038b4f09f98c86aa1212f5651
cp %{_builddir}/opa-fm-10.10.0.0.444/LICENSE %{buildroot}/usr/share/package-licenses/opa-fm/948af859e51811abec8ee00c3a27db28934270cf
%make_install ||:
## install_append content
mkdir -p %{buildroot}/usr/lib/systemd/system
install Esm/ib/src/linux/startup/opafm.service %{buildroot}/usr/lib/systemd/system/

mkdir -p %{buildroot}/usr/lib/opa-fm
install Esm/ib/src/linux/startup/opafmctrl \
Esm/ib/src/linux/startup/build.VIEO_HOST.release/opafmd \
%{buildroot}/usr/lib/opa-fm/

mkdir -p %{buildroot}/usr/share/opa-fm
install Esm/ib/src/linux/startup/opafm.xml \
Esm/ib/src/linux/startup/opafm_pp.xml \
Esm/ib/src/linux/startup/opafm_src.xml \
%{buildroot}/usr/share/opa-fm/

mkdir -p %{buildroot}/usr/lib/opa-fm/bin
install Esm/ib/src/linux/startup/fm_capture \
Esm/ib/src/linux/fm_cmd/build.VIEO_HOST.release/fm_cmd \
Esm/ib/src/linux/startup/fm_cmdall \
Esm/ib/test/smi/sm/build.VIEO_HOST.release/smpoolsize \
Esm/ib/src/linux/startup/fm_config/opafmconfigpp \
Esm/ib/src/linux/opafmvf/build.VIEO_HOST.release/opafmvf \
Esm/ib/src/linux/startup/fm_config/build.VIEO_HOST.release/config_check \
Esm/ib/src/linux/startup/fm_config/build.VIEO_HOST.release/config_convert \
Esm/ib/src/linux/startup/fm_config/config_diff \
Esm/ib/src/linux/startup/fm_config/config_generate \
Esm/ib/src/linux/startup/opafm \
Esm/ib/src/linux/startup/build.VIEO_HOST.release/opaxmlextract \
Esm/ib/src/linux/startup/build.VIEO_HOST.release/opaxmlfilter \
%{buildroot}/usr/lib/opa-fm/bin/

mkdir -p %{buildroot}/usr/lib/opa-fm/runtime
install Esm/ib/src/build.VIEO_HOST.release/sm \
Esm/ib/src/fe/fe_proc/build.VIEO_HOST.release/fe \
%{buildroot}/usr/lib/opa-fm/runtime

mkdir -p %{buildroot}/usr/share/man/man8
install Esm/ib/man/opafmcmd.8 \
Esm/ib/man/opafmcmdall.8 \
%{buildroot}/usr/share/man/man8/

mkdir -p %{buildroot}/usr/bin
ln -sf ../lib/opa-fm/bin/fm_cmd %{buildroot}/usr/bin/
ln -sf ../lib/opa-fm/bin/fm_cmdall %{buildroot}/usr/bin/
ln -sf ../lib/opa-fm/bin/opafmconfigpp %{buildroot}/usr/bin/
ln -sf ../lib/opa-fm/bin/opafmvf %{buildroot}/usr/bin/
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib/opa-fm/bin/config_check
/usr/lib/opa-fm/bin/config_convert
/usr/lib/opa-fm/bin/config_diff
/usr/lib/opa-fm/bin/config_generate
/usr/lib/opa-fm/bin/fm_capture
/usr/lib/opa-fm/bin/fm_cmd
/usr/lib/opa-fm/bin/fm_cmdall
/usr/lib/opa-fm/bin/opafm
/usr/lib/opa-fm/bin/opafmconfigpp
/usr/lib/opa-fm/bin/opafmvf
/usr/lib/opa-fm/bin/opaxmlextract
/usr/lib/opa-fm/bin/opaxmlfilter
/usr/lib/opa-fm/bin/smpoolsize
/usr/lib/opa-fm/opafmctrl
/usr/lib/opa-fm/opafmd
/usr/lib/opa-fm/runtime/fe
/usr/lib/opa-fm/runtime/sm

%files bin
%defattr(-,root,root,-)
/usr/bin/fm_cmd
/usr/bin/fm_cmdall
/usr/bin/opafmconfigpp
/usr/bin/opafmvf

%files data
%defattr(-,root,root,-)
/usr/share/opa-fm/opafm.xml
/usr/share/opa-fm/opafm_pp.xml
/usr/share/opa-fm/opafm_src.xml

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/opa-fm/31b5b4b9993aab20f8d12d5a46d638e962b77f9c
/usr/share/package-licenses/opa-fm/492fce15e8c89e8038b4f09f98c86aa1212f5651
/usr/share/package-licenses/opa-fm/5868056e5347f049ca07096a4a426c0e4a71a474
/usr/share/package-licenses/opa-fm/948af859e51811abec8ee00c3a27db28934270cf

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/opafmcmd.8
/usr/share/man/man8/opafmcmdall.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/opafm.service
